### PR TITLE
Persist preferred keyboard layout

### PR DESCRIPTION
**Pull request by itsjeyd**
cf. [OC-2504](https://tasks.opencraft.com/browse/OC-2504)

**Test instructions**

0. Add keyboard layouts to `XBLOCK_SETTINGS` in `lms.env.json`:

    ```json
    "XBLOCK_SETTINGS": {
        "skytap": {
            "keyboard_layouts": {
                "nl-be": "Dutch-Belgium",
                "uk": "English (UK)",
                "us": "English (US)",
                "fi": "Finnish",
                "fr": "French",
                "fr-be": "French-Belgium",
                "fr-ch": "French-Switzerland",
                "de": "German",
                "de-ch": "German-Switzerland",
                "is": "Icelandic",
                "it": "Italian",
                "jp": "Japanese",
                "no": "Norwegian",
                "pt": "Polish",
                "es": "Spanish"
            }
        }
    },
    ```

1. Add Skytap XBlock to a unit.

2. Access the unit in the LMS.
    * Observe that the default choice for the keyboard layout option is "English (US)".
    * Observe that the list of choices is sorted alphabetically.

3. Select a different option, then click "Launch".

4. Refresh the page. Observe that the keyboard layout option now defaults to the keyboard layout option you selected in the previous step.

**Reviewers**

- [x] @bdero

### CODE REVIEW

**Comment by bdero** [comment]
Hey @itsjeyd, great work here! The layout persists between refreshes and the layout configuration works.  I just noticed two small issues:

1. Dropdown had nothing in it:

   

   This is because there is no [default value](https://github.com/open-craft/xblock-skytap/pull/2/files#diff-d678185f8516d1615cae6845ef7d51d4R82). It was fine after I added some layouts to the xblock settings. Should we add a few (or perhaps all currently supported) layouts by default?

1. Hitting the launch button results in a TypeError:

   

   This is due to the default popup blocking behavior in Chrome. If we can't avoid using `window.open` in a callback, it would be helpful to alert the user since the popup block notification is very subtle:

   ```javascript
   var sharingPortal = window.open('https://www.skytap.com/', '_blank');
   if (sharingPortal == null) {
       alert("The browser's popup blocker prevented the exercise from being launched.")
   } else {
       sharingPortal.focus();
   }
   ```

**Comment by itsjeyd** [comment]
@bdero Thanks for the feedback! I incorporated it (9dd29370a39e9ad2479789074c92c437a2fff7e7, 4674da003f7fabc8a654efcc668a600d65bd7854) and added an integration test (d20d6ebe0e539da5807de33d0a949be4067496ca). The remaining commits just add some polish. Could you have another look please?

**Comment by bdero** [comment]
:+1:

- [x] I tested this: I added the XBlock to a unit in studio, verified the default "preferred keyboard layout" and keyboard layouts list is working. I verified that a Javascript alert pops up when a browser's internal popup blocker interrupts launching. Hitting the launch button calls the `launch` callback and saves the keyboard layout. I verified that the tests are working, and that they're properly running on CircleCI
- [x] I read through the code
- [x] I checked for accessibility issues
- [x] Includes documentation

**Comment by itsjeyd** [comment]
Thanks @bdero! Merging now.

**Pull request merged**
